version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:6.2
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 0s
    command: redis-server --requirepass ${REDIS_PASSWORD}
