version: '3.7'
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:6.2
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 0s
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    name: redis-data
