version: '3.7'
services:
  app:
    build:
      context: .
      args:
        NPM_TOKEN: "${NPM_TOKEN}"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 1s
    restart: on-failure
    # depends_on:
    #   redis:
    #     condition: service_healthy
    #   postgres:
    #     condition: service_healthy
    #   rabbitmq:
    #     condition: service_healthy
  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - '80:80'
  redis:
    env_file:
      - .env
    image: redis:6.2
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 0s
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
  postgres:
    env_file:
      - .env
    image: postgres:12
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 0s
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
        - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
        - ${RABBITMQ_MANAGMENT_PORT}:${RABBITMQ_MANAGMENT_PORT}
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-logs:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 0s
volumes:
  redis-data:
    name: redis-data
  postgres-data:
    name: postgres-data
  rabbitmq-data:
    name: rabbitmq-data
  rabbitmq-logs:
    name: rabbitmq-logs

