name: Build & Publish

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    outputs:
      image:
        description: "The unique name of the published docker image"
        value: ${{ jobs.build.outputs.image }}
env:
  PROJECT_ID: docker-and-k8s-complete-guide
  GAR_LOCATION: europe-central2
  REPOSITORY: test-project
  IMAGE: test-project

jobs:
  build:
    environment: ${{ inputs.env }} # gotta have it in order to access the secrets https://github.com/actions/runner/issues/1490#issuecomment-1717389283
    name: Build and publish
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.vars.outputs.image }}
    steps:
    - name: Set variables
      id: vars
      run: |-
        echo "image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v4

    # Auth
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # - name: Docker configuration
    - name: Docker configuration
      run: |-
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "${{ steps.vars.outputs.image }}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "${{ steps.vars.outputs.image }}"
