name: Tests

on: [workflow_call]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    environment: testing

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare environment
      run: |
        touch .env.test
        echo "REDIS_PASSWORD=${{ vars.REDIS_PASSWORD }}" >> $GITHUB_ENV
        echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> $GITHUB_ENV
        echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> $GITHUB_ENV
        echo "REDIS_USERNAME=${{ vars.REDIS_USERNAME }}" >> $GITHUB_ENV
    - name: Run tests
      run: docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit

