name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing

    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.test.yml"
